### ISSUE TITLE
schema not exist in $schema table when  create  schema.table  and no create schema

### ISSUE THREAD

**Issue by ouyangshourui** [MartinWeindel/presto-kudu#10]
presto:autoschema> CREATE TABLE autoschema.users (
                ->   user_id int,
                ->   first_name varchar,
                ->   last_name varchar
                -> ) WITH (
                ->  column_design = '{"user_id": {"key": true}}',
                ->  partition_design = '{"hash":[{"columns":["user_id"], "buckets": 2}]}',
                ->  num_replicas = 3
                -> ); 
CREATE TABLE

autoschema no exists when use `show schemas` command !

**Comment by MartinWeindel** [comment]
Resolved with your pull request #11. Thanks again!
