### ISSUE TITLE
Query results are inconsistent

### ISSUE THREAD

**Issue by yorkart** [MartinWeindel/presto-kudu#4]
presto: 0.193
presto-kudu: 0.193.1

```
select  col0, col1, col2, colN
from my_table 
where year=2018 and month=3 and day=7 and hour=2 
limit 1000
```

Sometimes can find data, sometimes can't.
When the results are empty, I try to comment some columns, and there may be some result to find out.

**Comment by yechangyao** [comment]
HI there

I have the same problem too.
when the range partition is {"lower":null,"upper":null}, the result of select count(*) is different.

when I set a specific range partition, it works fine.

**Comment by MartinWeindel** [comment]
Please provide more details which allows to reproduce the problem. There are so many thinkable causes, that it is impossible to get an idea.
Please try to isolate the origin:
- is it a problem of some inconsistent data of a Kudu tablet server?
- is it a problem of Kudu itself?
- is it a problem of the Kudu Java client?
- is it a problem of Presto?

Or try to provide a reproducible procedure description.

**Comment by MartinWeindel** [comment]
Can anybody reproduce this issue with Kudu 1.7.0? Thanks.

**Comment by yechangyao** [comment]
Hi, When I updated, I will test that. Please wait.

**Comment by yechangyao** [comment]
Hi I checked in the env with kudu client 1.7.0. 
The problem doesn't happen.

**Comment by MartinWeindel** [comment]
@yechangyao Thanks for checking.
