### ISSUE TITLE
KUDU-2343. java: properly reconnect to new leader master after failover

### ISSUE THREAD

**Issue by yechangyao** [MartinWeindel/presto-kudu#5]
Hi there

There is a bug that kudu-client doesn't work properly when leader master changed, And I think presto-kudu is also affected by this bug.

https://github.com/apache/kudu/commit/f8ae5117b257887e6ef222f751ad7cca5640d4d9
Please check.

**Comment by MartinWeindel** [comment]
According to https://issues.apache.org/jira/browse/KUDU-2343, this bug is not resolved yet.
As soon as the Kudu Java client 1.7.0 is released, I will release a new version.

**Comment by MartinWeindel** [comment]
As the latest release 0.197.1 uses Kudu Java client 1.7.0, this issue should be fixed.
