### ISSUE TITLE
Why not to contribute this to prestodb/presto?

### ISSUE THREAD

**Issue by kokosing** [MartinWeindel/presto-kudu#6]
That way it will be easier to maintain this project and larger community could contribute to this.

**Comment by MartinWeindel** [comment]
I'm very open to contributing this project to Prestodb. It was never the idea to keep this plugin separate forever.
There are a fews things to be done first:
- the packages must be renamed (easy)
- the souce code must be reformatted to conform the codestyle of presto (some work)
- a solution for running the tests in the Presto build environment (unclear to me)

Initially the main reason to keep this plugin separate was to be independent of the Prestodb release cycle. The code base is quite complete now, so this is not important anymore.

It would be very helpful, if somebody could help me with the integration of the tests into the Presto build environment. At the moment, I have also some helper projects for building Kudu and providing a docker container with Kudu master & tserver. I don't know how to migrate or substitute that stuff.

**Comment by kokosing** [comment]
Of course I can help you :)

Having docker to provide Kudu server sounds ok to me. You might want to provide some script which could make it a bit easier to run, something like we have for hive: https://github.com/prestodb/presto/blob/master/presto-hive-hadoop2/bin/run_hive_tests.sh
Having this it would be much easier to setup test automation (CI).
Notice you should be using variables for things like server or port, these should not be hardcoded (https://github.com/MartinWeindel/presto-kudu/blob/master/src/test/java/ml/littlebulb/presto/kudu/TpchKuduQueryRunner.java#L57)

Please post a PR and we will try to fix the remaining issues as we go with the review.

Thank you!

**Comment by kokosing** [comment]
Notice that we are using https://github.com/prestodb/docker-images/ to store the docker images we are using in automation. This might be needed if you are using custom Kudu docker image.

**Comment by MartinWeindel** [comment]
Thanks for your comments!
I just posted a [PR](https://github.com/prestodb/presto/pull/10388), but this does not yet include changes according to your comments.

**Comment by MartinWeindel** [comment]
Contributing to Prestodb takes much more time than expected.
Currently I'm blocked by the outstanding review & merge of a depending pull request [Add column properties to SQL parser](https://github.com/prestodb/presto/pull/10553).

**Comment by kokosing** [comment]
You are doing very well. It is typical to Presto community that things are being merged slowly, it takes time to fully review the code and a lot of things are happening at the same time. All the people involved in the project need to respect priorities in their companies (business driven). We see a value in having Kudu connector merged in, but most of handling community contribution is a volunteer work. 

Please be patient and keep pinging people ;)

**Comment by kokosing** [comment]
Thank you!
