### ISSUE TITLE
It would be better to create a fat jar instead of a zip

### ISSUE THREAD

**Issue by yechangyao** [MartinWeindel/presto-kudu#7]
Hi.
Is it possible to create a fat jar? Maybe it will be easy to deploy to servers.

In my environment, I use Slider to start presto worker on yarn. It needs to copy presto-kudu to yarn containers. But due to slider's configuration rule,  I need to specify the names of every dependency jar in slider configuration. That's really annoying.

It would be very appreciated if you can think about it.

**Comment by MartinWeindel** [comment]
Rejected. Not my problem.
