### ISSUE TITLE
Getting different results for the same query

### ISSUE THREAD

**Issue by KrzysztofKowalczyk** [MartinWeindel/presto-kudu#9]
Hi,

I'm using Presto with Kudu connector, thanks for good work. 
I noticed a strange behaviour and I am try to pinpoint is it problem with Kudu, Presto or the connector.

What happens:
- I insert to Kudu through Java API with upsert (I might be inserting exactly the same data sometimes)
- I query a subset that should not be changing anymore
- I see different results with consecutive queries that fluctuate between few values over and over to eventually settle on one (the highest one from what I can tell, not sure)
- I have hash partitions thus the partition that I am querying might have inserts, compactions etc, but inserts should not change the result of the query
- It does not happen all the time
- I have only one master and one tablet server

Can you think of something in Presto or connector implementation that could cause it? 
Or should I focus my attention on Kudu.

**Comment by MartinWeindel** [comment]
The symptoms you have descripted look very similar to the bug I have just fixed.
There was a slight inconsistency in the class KuduRecordCursor on handling the double loop of the Kudu scanner. If the inner loop returned no results, the outer loop was also finished. But it can happen that a batch returned from KuduScanner is empty and more results are returned in later batches. In combination with prefetching and timing this could result in randomly incomplete result sets.
Please try the new release [0.203.2](https://github.com/MartinWeindel/presto-kudu/releases/tag/v0.203.2).

**Comment by KrzysztofKowalczyk** [comment]
Oh great! Will have a look. 
I just tried to use your Kudu Docker image with Presto to try to replicate it, but it seems Kudu advertise docker hostname as ip and exceptions are being thrown because I run Presto from host and kudu in docker. Any ways around it?

**Comment by MartinWeindel** [comment]
For testing, I always use the Kudu docker container with host network, e.g.
`docker run --rm -d --name apache-kudu --net=host usuresearch/kudu-docker-slim:release-v1.7.0-1`

**Comment by KrzysztofKowalczyk** [comment]
Ah, of course, thanks.

**Comment by MartinWeindel** [comment]
closed as resolved
